config/routes.rb
Rails.application.routes.draw do
  devise_for :employers
  devise_for :users
  resources :applicants
  
  # resources :users
  # get 'home/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "home#index"
end

app/models/applicant.rb
class Applicant < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/applicants_controller.rb
class ApplicantsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_applicant, only: %i[ show edit update destroy ]

  # GET /applicants or /applicants.json
  def index
    @applicants = Applicant.all
  end

  # GET /applicants/1 or /applicants/1.json
  def show
  end

  # GET /applicants/new
  def new
    @applicant = Applicant.new
  end

  # GET /applicants/1/edit
  def edit
  end

  # POST /applicants or /applicants.json
  def create
    @applicant = Applicant.new(applicant_params)

    respond_to do |format|
      if @applicant.save
        format.html { redirect_to applicant_url(@applicant), notice: "Applicant was successfully created." }
        format.json { render :show, status: :created, location: @applicant }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @applicant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /applicants/1 or /applicants/1.json
  def update
    respond_to do |format|
      if @applicant.update(applicant_params)
        format.html { redirect_to applicant_url(@applicant), notice: "Applicant was successfully updated." }
        format.json { render :show, status: :ok, location: @applicant }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @applicant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /applicants/1 or /applicants/1.json
  def destroy
    @applicant.destroy

    respond_to do |format|
      format.html { redirect_to applicants_url, notice: "Applicant was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_applicant
      @applicant = Applicant.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def applicant_params
      params.fetch(:applicant, {})
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    # def current_user
    #     @current_user ||= User.find(session[:user_id]) if session[:user_id]
    # end
    # helper_method :current_user  
    # protected
    
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/applicants_helper.rb
module ApplicantsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/applicants/_applicant.html.erb
<div id="<%= dom_id applicant %>">
</div>

app/views/applicants/_form.html.erb
<%= form_with(model: applicant) do |form| %>
  <% if applicant.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(applicant.errors.count, "error") %> prohibited this applicant from being saved:</h2>

      <ul>
        <% applicant.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/applicants/edit.html.erb
<h1>Editing applicant</h1>

<%= render "form", applicant: @applicant %>

<br>

<div>
  <%= link_to "Show this applicant", @applicant %> |
  <%= link_to "Back to applicants", applicants_path %>
</div>

app/views/applicants/index.html.erb
<%# <p style="color: green">= notice</p> %>

<h1>welcome Applicants to job portal</h1>

<%# <div id="applicants"> %>
  <%# @applicants.each do |applicant| %>
    <%#= render applicant %>
    <%# <p> %>
      <%#= link_to "Show this applicant", applicant %>
    <%# </p> %>
  <%# end %>
<%# </div> %>

<%= link_to "view all jobs" %>
<%= button_to "logout", destroy_user_session_path, method: :delete  %>

app/views/applicants/new.html.erb
<h1>New applicant</h1>

<%= render "form", applicant: @applicant %>

<br>

<div>
  <%= link_to "Back to applicants", applicants_path %>
</div>

app/views/applicants/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @applicant %>

<div>
  <%= link_to "Edit this applicant", edit_applicant_path(@applicant) %> |
  <%= link_to "Back to applicants", applicants_path %>

  <%= button_to "Destroy this applicant", @applicant, method: :delete %>
</div>

app/views/home/index.html.erb
<h1>WELCOME TO JOB PORTAL</h1><br><br>
<h2><%= link_to "Employer portal" ,employers_path   %></h2>
<h2><%= link_to "Applicant portal" , applicants_path %></h2>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>JobPortal</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>